title: Justin Bisuna
logo: /assets/img/Justin Bisuna_Portrait.jpg
#description: text below image
# show_downloads: true
# theme: jekyll-theme-minimal
theme: jekyll-theme-leap-day

# OTHER THEMES
# Architect
# Cayman
# Dinky
# Hacker
# Leap day
# Midnight
# Minima
# Minimal
# Modernist
# Slate
# Tactile
# Time machine
