title: Justin Bisuna
logo: /assets/img/Justin_Bisuna_Portrait.png
description: |
  **Computer Engineering Student | De La Salle University (Graduating Feb 2025, Cum Laude, Gold Thesis Award)**
  
  - Led proof-of-concept projects at PwC's AI Lab using AWS technologies.
  - Served as Associate Vice Chairperson for HR & Development at the Council of Student Organization, focusing on well-being and management.
  - Skilled in Data Science, Machine Learning, and Project Management.
  - Proven ability to implement technology-driven solutions.







# show_downloads: true
theme: jekyll-theme-minimal

# OTHER THEMES
# Architect
# Cayman
# Dinky
# Hacker
# Leap day
# Midnight
# Minima
# Minimal
# Modernist
# Slate
# Tactile
# Time machine
