title: Justin Bisuna
logo: /assets/img/Justin_Bisuna_Portrait.png
description: |
  Justin Bisuna is a Computer Engineering student from De La Salle University, graduating in February 2025 with Cum Laude honors and Gold Thesis Awardee. He was one of the pioneers of PwC's Artificial Intelligence Lab, where he led the development of proof-of-concept projects using AWS technologies to improve business processes. Justin also served as the Associate Vice Chairperson for Human Resource and Development at his university's Council of Student Organization (CSO), focusing on well-being and organizational management. He is skilled in data science, machine learning, and project management, with a strong track record of implementing technology-driven solutions in various projects.

summary: |
  **Computer Engineering Student | De La Salle University (Graduating Feb 2025, Cum Laude, Gold Thesis Award)**
  
  - Led proof-of-concept projects at PwC's AI Lab using AWS technologies.
  - Served as Associate Vice Chairperson for HR & Development at the Council of Student Organization, focusing on well-being and management.
  - Skilled in Data Science, Machine Learning, and Project Management.
  - Proven ability to implement technology-driven solutions.







# show_downloads: true
theme: jekyll-theme-minimal

# OTHER THEMES
# Architect
# Cayman
# Dinky
# Hacker
# Leap day
# Midnight
# Minima
# Minimal
# Modernist
# Slate
# Tactile
# Time machine
