title: Justin Bisuna
logo: /assets/img/Justin_Bisuna_Portrait.png
description: Justin Bisuna is a Computer Engineering student at De La Salle University, graduating in February 2025 with Cum Laude honors and a Gold Thesis Award. He played a key role in establishing PwC's Artificial Intelligence Lab and led AWS-based proof-of-concept projects. As Associate Vice Chairperson for Human Resource and Development at his university's Council of Student Organization, he focused on well-being and management. Justin is skilled in data science, machine learning, and project management, with a strong track record of implementing technology-driven solutions.


# show_downloads: true
theme: jekyll-theme-minimal

# OTHER THEMES
# Architect
# Cayman
# Dinky
# Hacker
# Leap day
# Midnight
# Minima
# Minimal
# Modernist
# Slate
# Tactile
# Time machine
